### ISSUE TITLE
non-yellow door color inputs will mistakenly tell the user they have won

### ISSUE THREAD

**Issue by aetimmes** [StevenGaughran/python_learning#1]
https://github.com/StevenGaughran/python_learning/blob/279368ef7c4a6caa539c5c5e3a3b8b19f9771f87/DAY_3_treasure_island.py#L42-L48

Per the [flowchart](https://viewer.diagrams.net/?highlight=0000ff&edit=_blank&layers=1&nav=1&title=Treasure%20Island%20Conditional.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1oDe4ehjWZipYRsVfeAx2HyB7LCQ8_Fvi%26export%3Ddownload) included in the source code, entering a non-yellow door color should result in a 'Game Over', but it instead congratulates the user, as below:

```
$ python3.8 DAY_3_treasure_island.py

...

You arrive at the island unharmed. There is a house with 3 doors, behind one of which sits the treasure you seek. One red, one yellow and one blue.
Which colour do you choose? it's spelled 'color', you pinko commie
Congratulations! You find the treasure and book a flight to Vegas. The End.
```

**Comment by StevenGaughran** [comment]
THIS IS A FEATURE NOT A BUG WORKING AS INTENDED SHIP IT BAY-BEE

Joking aside, thanks for checking. I believe I have fixed it.
